---
creator_name_type:
  type: string
  form:
    required: true
    multiple: false
    type: select
creator_family_name:
  type: string
  form:
    required: true
    multiple: false
    type: text
    display_for:
      - personal
creator_given_name:
  type: string
  form:
    required: true
    multiple: false
    type: text
    display_for:
      - personal
creator_orcid:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - personal
creator_institutional_relationship:
  type: string
  form:
    required: false
    multiple: false
    type: select
    authority: HykuAddons::InstitutionalRelationshipService
    display_for:
      - personal
creator_organization_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - organizational
creator_ror:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - organizational
creator_grid:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - organizational
creator_wikidata:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - organizational
creator_isni:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - personal
      - organizational

