---
date_submitted_year:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateYearService
date_submitted_month:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateMonthService
date_submitted_day:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateDayService

