---
date_accepted_year:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateYearService
date_accepted_month:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateMonthService
date_accepted_day:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateDayService

