---
# DOI needs to be multiple for backwards compatibility, however it needs to display only a single input field
doi:
  type: string
  predicate: http://purl.org/ontology/bibo/doi
  multiple: true
  index_keys:
    - doi_tesim
    - doi_ssi
  form:
    required: false
    primary: true
    multiple: true
    type: text
    input: single_multi_value
