---
event_date_year:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateYearService
event_date_month:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateMonthService
event_date_day:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateDayService

