---
related_exhibition_date_year:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateYearService
related_exhibition_date_month:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateMonthService
related_exhibition_date_day:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::DateDayService

