---
rights_statement:
  predicate: http://www.europeana.eu/schemas/edm/rights
  multiple: false
  index_keys:
    - rights_statement_tesim
  form:
    required: false
    primary: false
    multiple: false
    type: select
    authority: HykuAddons::RightsStatementService
