inherit_gem:
  bixby: bixby_default.yml

AllCops:
  UseCache: true
  TargetRubyVersion: 2.5
  DisplayCopNames: true

RSpec/ExampleLength:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  Exclude:
    - "lib/hyku_addons/engine.rb"

Metrics/BlockLength:
  Exclude:
    - "lib/hyku_addons/engine.rb"
    - "lib/tasks/*.rake"
    - "spec/**/*.rb"
