inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'app/jobs/hyku_addons/post_migration_fix_work_job.rb'
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*'
    - 'config/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/hyku_addons/csv_entry.rb'
    - 'app/services/bolognese/readers/base_work_reader.rb'
    - 'app/services/hyku_addons/validations/solr_entry_validation_service.rb'
    - 'app/services/hyku_addons/validations/entry_validation_service.rb'
    - 'lib/hyku_addons/engine.rb'
    - 'app/models/nsu_generic_work.rb'
    - 'app/models/nsu_article.rb'

Metrics/LineLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'spec/jobs/register_doi_job_spec.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'
    - 'app/models/concerns/hyku_addons/account_behavior.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/models/concerns/hyku_addons/generic_work_overrides.rb'
    - 'app/models/concerns/hyku_addons/solr_document_behavior.rb'
    - 'app/models/concerns/hyku_addons/work_base.rb'
    - 'app/forms/concerns/hyku_addons/collection_form_behavior.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/pacific_article.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'app/views/hyku/api/v1/work/_work.json.jbuilder'
    - 'app/models/concerns/hyku_addons/account_behavior.rb'
    - 'bin/transform_export_batch.rb'
    - 'hyku_addons.gemspec'
    - 'lib/hyku_addons/engine.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'
    - 'config/features.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/concerns/hyku_addons/catalog_controller_behavior.rb'
    - 'app/controllers/concerns/hyku_addons/importer_controller_behavior.rb'
    - 'app/forms/concerns/hyku_addons/generic_work_form_overrides.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/hyku_addons/csv_entry.rb'
    - 'app/parsers/hyku_addons/csv_parser.rb'
    - 'app/services/bolognese/readers/base_work_reader.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'app/services/hyku_addons/validations/solr_entry_validation_service.rb'
    - 'bin/transform_export_batch.rb'
    - 'lib/hyku_addons/engine.rb'
    - 'lib/tasks/account.rake'
    - 'spec/**/*.rb'
    - 'app/controllers/concerns/hyku_addons/search_controller_behavior.rb'
    - 'app/forms/hyrax/nsu_generic_work_form.rb'
    - 'app/forms/hyrax/nsu_article_form.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'bin/transform_export_batch.rb'
    - 'lib/hyku_addons/engine.rb'
    - 'app/services/hyku_addons/validations/solr_entry_validation_service.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/hyku_addons/multiple_metadata_fields_helper.rb'
    - 'bin/transform_export_batch.rb'
    - 'lib/hyku_addons/engine.rb'
    - 'app/services/hyku_addons/validations/solr_entry_validation_service.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/actors/hyku_addons/actors/json_fields_actor.rb'
    - 'app/forms/concerns/hyku_addons/work_form.rb'
    - 'app/models/hyku_addons/csv_entry.rb'
    - 'app/services/bolognese/writers/ris_writer_behavior.rb'
    - 'app/controllers/concerns/hyku_addons/importer_controller_behavior.rb'
    - 'bin/transform_export_batch.rb'
    - 'lib/hyku_addons/engine.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/**/*'
    - 'spec/lib/**/*'
    - 'spec/requests/api_v1_work_spec.rb'
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'
    - 'spec/services/hyku_addons/entry_validation_service_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/helpers/work_forms_context.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'

Style/RescueModifier:
  Exclude:
    - 'bin/transform_export_batch.rb'

Style/SymbolProc:
  Exclude:
    - 'app/models/concerns/hyku_addons/account_behavior.rb'

Style/StructInheritance:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - 'lib/hyku_addons/engine.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/renderers/**/*'

Rails/Date:
  Exclude:
    - 'spec/services/bolognese/readers/generic_work_reader_spec.rb'

Rails/FindBy:
  Exclude:
    - 'app/models/hyku_addons/csv_entry.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'app/services/hyku_addons/jwt_cookies_service.rb'

RSpec/LetSetup:
  Exclude:
    - 'spec/features/bulkrax_import_spec.rb'

Performance/RedundantSortBy:
  Exclude:
    - 'app/renderers/hyrax/renderers/work_metadata_diff_renderer.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/hydra-derivatives.rb'
    - 'Gemfile'

Lint/HandleExceptions:
  Exclude:
    - 'app/models/hyku_addons/csv_entry.rb'
