---
attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
    - title_tesim
    - title_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  alt_title:
    type: string
    predicate: http://purl.org/dc/terms/alternative
    multiple: true
    index_keys:
    - alt_title_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys:
    - creator_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
    subfields:
      creator_name_type:
        type: string
        form:
          required: true
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      creator_family_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
          - Personal
      creator_given_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_middle_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_suffix:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_role:
        type: string
        form:
          required: false
          multiple: true
          type: select
          authority: HykuAddons::RoleService
          display_for:
          - Personal
      creator_institution:
        type: string
        form:
          required: false
          multiple: true
          type: text
          display_for:
          - Personal
      creator_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_institutional_email:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_organization_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
  date_published:
    type: string
    predicate: http://purl.org/dc/terms/available
    multiple: false
    index_keys:
    - date_published_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: date
  date_published_text:
    type: string
    predicate: http://purl.org/dc/terms/date
    multiple: false
    index_keys:
    - date_published_text_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
    - abstract_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: textarea
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_sim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::ResourceTypesService
      include_blank: true
      input: single_multi_value_select
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys:
    - license_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LicenseService
      include_blank: true
  place_of_publication:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Place
    multiple: true
    index_keys:
    - place_of_publication_tesim
    - place_of_publication_sim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  language:
    predicate: http://purl.org/dc/elements/1.1/language
    multiple: true
    index_keys:
    - language_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LanguageService
      include_blank: true
  subject_text:
    type: string
    predicate: http://purl.org/dc/terms/subject
    multiple: true
    index_keys:
    - subject_text_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  mesh:
    type: string
    predicate: http://purl.org/dc/terms/MESH
    multiple: true
    index_keys:
    - mesh_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: true
    index_keys:
    - add_info_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: textarea
  advisor:
    type: string
    predicate: http://bibframe.org/vocab/Person
    multiple: true
    index_keys:
    - advisor_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  publisher:
    predicate: http://purl.org/dc/elements/1.1/publisher
    multiple: true
    index_keys:
    - publisher_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  source:
    predicate: http://purl.org/dc/terms/source
    multiple: true
    index_keys:
    - source_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  journal_frequency:
    type: string
    predicate: http://purl.org/dc/terms/Frequency
    multiple: false
    index_keys:
    - journal_frequency_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  funding_description:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/spn
    multiple: true
    index_keys:
    - funding_description_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  citation:
    type: string
    predicate: http://purl.org/dc/terms/bibliographicCitation
    multiple: true
    index_keys:
    - citation_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  table_of_contents:
    type: string
    predicate: http://bibframe.org/vocab/tableOfContents
    multiple: false
    index_keys:
    - table_of_contents_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  references:
    type: string
    predicate: http://purl.org/dc/terms/references
    multiple: true
    index_keys:
    - references_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  extent:
    type: string
    predicate: http://purl.org/dc/terms/extent
    multiple: false
    index_keys:
    - extent_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  medium:
    type: string
    predicate: http://purl.org/dc/terms/medium
    multiple: true
    index_keys:
    - medium_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  library_of_congress_classification:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/ClassificationLcc
    multiple: true
    index_keys:
    - library_of_congress_classification_tesim
    - library_of_congress_classification_sim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  committee_member:
    type: string
    predicate: https://www.w3.org/ns/activitystreams#Person
    multiple: true
    index_keys:
    - committee_member_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  time:
    type: string
    predicate: http://purl.org/dc/terms/temporal
    multiple: false
    index_keys:
    - time_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  part_of:
    type: string
    predicate: http://purl.org/dc/terms/partOf
    multiple: true
    index_keys:
    - part_of_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  rights_statement:
    predicate: http://www.europeana.eu/schemas/edm/rights
    multiple: false
    index_keys:
    - rights_statement_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      authority: HykuAddons::RightsStatementService
  qualification_subject_text:
    type: string
    predicate: http://www.w3.org/ns/hydra/core#subject
    multiple: true
    index_keys:
    - qualification_subject_text_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  qualification_grantor:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/grantingInstitution
    multiple: false
    index_keys:
    - qualification_grantor_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  qualification_level:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/degree
    multiple: false
    index_keys:
    - qualification_level_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      authority: HykuAddons::QualificationLevelService
  qualification_name:
    type: string
    predicate: http://schema.org/qualifications
    multiple: false
    index_keys:
    - qualification_name_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      authority: HykuAddons::QualificationNameService
  is_format_of:
    type: string
    predicate: http://purl.org/dc/terms/isFormatOf
    multiple: true
    index_keys:
    - is_format_of_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  source_identifier:
    type: string
    predicate: http://www.w3.org/ns/prov#wasDerivedFrom
    multiple: false
    index_keys:
    - source_identifier_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
