---
attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
      - title_tesim
      - title_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  alt_title:
    type: string
    predicate: http://purl.org/dc/terms/alternative
    multiple: false
    index_keys:
      - alt_title_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys:
      - resource_type_tesim
      - resource_type_sim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::ResourceTypesService
      include_blank: true
      input: single_multi_value_select
  alt_class:
    predicate: http://mappings.dbpedia.org/index.php/OntologyClass:Type
    multiple: true
    index_keys:
      - alt_class_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::AltClassService
      include_blank: true
      input: single_multi_value_select
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys:
      - creator_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
    subfields:
      creator_name_type:
        type: string
        form:
          required: true
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      creator_family_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Personal
      creator_given_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_middle_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_suffix:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_culture:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_date:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institution:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institutional_email:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::InstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
            - Personal
      creator_organization_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
            - Organizational
      creator_role:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::RoleService
          include_blank: true
          display_for:
            - Personal
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
    - abstract_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: textarea
  inscription:
    predicate: https://schema.org/additionalName
    multiple: true
    index_keys:
      - inscription_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  keyword:
    predicate: http://purl.org/dc/elements/1.1/relation
    multiple: true
    index_keys:
      - keyword_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  official_link:
    type: string
    predicate: http://schema.org/url
    multiple: false
    index_keys:
      - official_link_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  location:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/physicalLocation
    multiple: false
    index_keys:
      - location_tesim
      - location_sim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  doi:
    type: string
    predicate: http://purl.org/ontology/bibo/doi
    multiple: true
    index_keys:
      - doi_ssi
    form:
      required: false
      primary: false
      multiple: true
      type: text
      input: single_multi_value
  media:
    type: string
    predicate: http://www.loc.gov/mods/rdf/v1#physicalForm
    multiple: true
    index_keys:
      - media_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  extent:
    type: string
    predicate: http://purl.org/dc/terms/extent
    multiple: false
    index_keys:
      - extent_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  relation:
    predicate: http://purl.org/dc/terms/relation
    multiple: false
    index_keys:
      - relation_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys:
      - license_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LicenseService
  rights:
    type: string
    predicate: http://purl.org/dc/terms/accessRights
    multiple: true
    index_keys:
      - rights_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  rights_holder:
    type: string
    predicate: http://purl.org/dc/terms/rightsHolder
    multiple: true
    index_keys:
      - rights_holder_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  rights_statement:
    predicate: http://www.europeana.eu/schemas/edm/rights
    multiple: false
    index_keys:
      - rights_statement_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: select
      authority: HykuAddons::RightsStatementService
  rights_statement_text:
    type: string
    predicate: http://purl.org/dc/elements/1.1/rights
    multiple: false
    index_keys:
      - rights_statement_text_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  source:
    predicate: http://purl.org/dc/terms/source
    multiple: true
    index_keys:
      - source_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  style_period:
    predicate: https://schema.org/pattern
    multiple: true
    index_keys:
      - style_period_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::StylePeriodService
  library_of_congress_subject_headings_text:
    type: string
    predicate: https://id.loc.gov/ontologies/bibframe.html#c_ClassificationLcc
    multiple: true
    index_keys:
      - library_of_congress_subject_headings_text_tesim
      - library_of_congress_subject_headings_text_sim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: false
    index_keys:
      - add_info_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: textarea
