attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
      - title_tesim
      - title_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  alt_title:
    type: string
    predicate: http://purl.org/dc/terms/alternative
    multiple: true
    index_keys:
      - alt_title_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys:
      - resource_type_tesim
      - resource_type_sim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::ResourceTypesService
      include_blank: true
      input: single_multi_value_select
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys:
      - creator_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
    subfields:
      creator_name_type:
        type: string
        form:
          required: true
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      creator_family_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Personal
      creator_given_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Personal
      creator_middle_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_suffix:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institution:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institutional_email:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal      
      creator_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::InstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
            - Personal
      creator_role:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::RoleService
          include_blank: true
          display_for:
          - Personal      
      creator_organization_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
            - Organizational
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
      - abstract_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: textarea
  keyword:
    predicate: http://purl.org/dc/elements/1.1/relation
    multiple: true
    index_keys:
      - keyword_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  subject:
    predicate: http://purl.org/dc/elements/1.1/subject
    multiple: true
    index_keys:
      - subject_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::SubjectService
  preprint_doi:
    type: string
    predicate: http://purl.org/dc/terms/identifier
    multiple: true
    index_keys:
      - preprint_doi_tesim
    form:
      required: false
      multiple: true
      type: text
      authority: null
      primary: true    
  doi:
    type: string
    predicate: http://purl.org/ontology/bibo/doi
    multiple: true
    index_keys:
      - doi_ssi
    form:
      required: false
      primary: true
      multiple: true
      type: text
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys:
      - license_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LicenseService
  rights_holder:
    type: string
    predicate: http://purl.org/dc/terms/rightsHolder
    multiple: true
    index_keys:
      - rights_holder_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  rights_statement:
    predicate: http://www.europeana.eu/schemas/edm/rights
    multiple: false
    index_keys:
      - rights_statement_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: select
      authority: HykuAddons::RightsStatementService
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: false
    index_keys:
      - add_info_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: textarea
  language:
    predicate: http://purl.org/dc/elements/1.1/language
    multiple: true
    index_keys:
      - language_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LanguageService
  funder:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/fnd
    multiple: true
    index_keys:
      - funder_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
    subfields:
      funder_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          input: controlled_vocabulary
          attributes:
            data:
              field_name: ubiquity_funder_name
              autocomplete-url: /authorities/search/crossref/funders
              autocomplete: funder
      funder_doi:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_award:
        type: string
        form:
          required: false
          multiple: true
          type: text