---
attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
    - title_tesim
    - title_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_sim
    form:
      required: true
      primary: true
      multiple: false
      type: select
      authority: HykuAddons::ResourceTypesService
      include_blank: true
      input: single_multi_value_select
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys:
    - creator_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
    subfields:
      creator_name_type:
        type: string
        form:
          required: true
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      creator_family_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
          - Personal
      creator_given_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
          - Personal
      creator_middle_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_suffix:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_profile_visibility:
        type: string
        form:
          required: false
          multiple: false
          type: hidden
          display_for:
          - Personal
      creator_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::InstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
          - Personal
      creator_institutional_email:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      creator_organization_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      creator_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
          - Organizational
  alt_email:
    type: string
    predicate: http://schema.org/email
    multiple: true
    index_keys:
    - alt_email_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
    - abstract_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: textarea
  keyword:
    predicate: http://purl.org/dc/elements/1.1/relation
    multiple: true
    index_keys:
    - keyword_tesim
    form:
      required: false
      primary: true
      multiple: true
      type: text
  subject:
    predicate: http://purl.org/dc/elements/1.1/subject
    multiple: true
    index_keys:
    - subject_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: select
      authority: HykuAddons::SubjectService
  date_published:
    type: string
    predicate: http://purl.org/dc/terms/available
    multiple: false
    index_keys:
    - date_published_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: date
  alternate_identifier:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Local
    multiple: true
    index_keys:
    - alternate_identifier_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
    subfields:
      alternate_identifier:
        type: string
        form:
          multiple: false
          required: false
          type: text
      alternate_identifier_type:
        type: string
        form:
          required: false
          multiple: false
          type: text
  library_of_congress_classification:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/ClassificationLcc
    multiple: true
    index_keys:
    - library_of_congress_classification_tesim
    - library_of_congress_classification_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  dewey:
    type: string
    predicate: http://schema.org/CategoryCode
    multiple: false
    index_keys:
    - dewey_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  related_identifier:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/identifiedBy
    multiple: true
    index_keys:
    - related_identifier_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
    subfields:
      related_identifier:
        type: string
        form:
          multiple: false
          required: false
          type: text
      related_identifier_type:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::RelatedIdentifierTypeService
          include_blank: true
      relation_type:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::RelationTypeService
          include_blank: true
  adapted_from:
    type: string
    predicate: http://purl.org/dc/elements/1.1/source
    multiple: false
    index_keys:
    - adapted_from_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  additional_links:
    type: string
    predicate: http://schema.org/significantLinks
    multiple: false
    index_keys:
    - additional_links_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  related_material:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/relatedTo
    multiple: false
    index_keys:
    - related_material_tesim
    - related_material_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  related_url:
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
    multiple: true
    index_keys:
    - related_url_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  source:
    predicate: http://purl.org/dc/terms/source
    multiple: true
    index_keys:
    - source_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  isbn:
    type: string
    predicate: http://purl.org/ontology/bibo/isbn
    multiple: false
    index_keys:
    - isbn_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  issn:
    type: string
    predicate: http://purl.org/ontology/bibo/issn
    multiple: false
    index_keys:
    - issn_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  eissn:
    type: string
    predicate: http://purl.org/ontology/bibo/eissn
    multiple: false
    index_keys:
    - eissn_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  publisher:
    predicate: http://purl.org/dc/elements/1.1/publisher
    multiple: true
    index_keys:
    - publisher_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  place_of_publication:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Place
    multiple: true
    index_keys:
    - place_of_publication_tesim
    - place_of_publication_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  citation:
    type: string
    predicate: http://purl.org/dc/terms/bibliographicCitation
    multiple: false
    index_keys:
    - citation_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  funder:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/fnd
    multiple: true
    index_keys:
    - funder_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
    subfields:
      funder_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          input: controlled_vocabulary
          attributes:
            data:
              field_name: ubiquity_funder_name
              autocomplete-url: "/authorities/search/crossref/funders"
              autocomplete: funder
      funder_doi:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
      funder_award:
        type: string
        form:
          required: false
          multiple: true
          type: text
  project_name:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/CollectiveTitle
    multiple: true
    index_keys:
    - project_name_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  fndr_project_ref:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/awards
    multiple: false
    index_keys:
    - fndr_project_ref_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  funding_description:
    type: string
    predicate: http://id.loc.gov/vocabulary/relators/spn
    multiple: false
    index_keys:
    - funding_description_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  event_title:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Event
    multiple: true
    index_keys:
    - event_title_tesim
    - event_title_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  event_location:
    type: string
    predicate: http://bibframe.org/vocab/eventPlace
    multiple: true
    index_keys:
    - event_location_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  event_date:
    type: string
    predicate: http://bibframe.org/vocab/eventDate
    multiple: true
    index_keys:
    - event_date_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: date
  related_exhibition:
    type: string
    predicate: http://schema.org/ExhibitionEvent
    multiple: true
    index_keys:
    - related_exhibition_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  related_exhibition_venue:
    type: string
    predicate: http://schema.org/EventVenue
    multiple: true
    index_keys:
    - related_exhibition_venue_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  related_exhibition_date:
    type: string
    predicate: http://schema.org/Date
    multiple: true
    index_keys:
    - related_exhibition_date_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: date
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys:
    - license_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      authority: HykuAddons::LicenseService
      include_blank: true
  rights_holder:
    type: string
    predicate: http://purl.org/dc/terms/rightsHolder
    multiple: true
    index_keys:
    - rights_holder_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  rights_statement:
    predicate: http://www.europeana.eu/schemas/edm/rights
    multiple: true
    index_keys:
    - rights_statement_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      include_blank: false
      authority: HykuAddons::RightsStatementService
  rights_statement_text:
    type: string
    predicate: http://purl.org/dc/elements/1.1/rights
    multiple: false
    index_keys:
    - rights_statement_text_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  contributor:
    predicate: http://purl.org/dc/elements/1.1/contributor
    multiple: true
    index_keys:
    - contributor_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
    subfields:
      contributor_name_type:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      contributor_family_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      contributor_given_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      contributor_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
      contributor_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::ContributorInstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
          - Personal
      contributor_organization_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      contributor_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      contributor_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      contributor_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Organizational
      contributor_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
          - Personal
          - Organizational
  medium:
    type: string
    predicate: http://purl.org/dc/terms/medium
    multiple: true
    index_keys:
    - medium_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
  extent:
    type: string
    predicate: http://purl.org/dc/terms/extent
    multiple: false
    index_keys:
    - extent_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  duration:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/duration
    multiple: true
    index_keys:
    - duration_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  is_format_of:
    type: string
    predicate: http://purl.org/dc/terms/isFormatOf
    multiple: true
    index_keys:
    - is_format_of_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  language:
    predicate: http://purl.org/dc/elements/1.1/language
    multiple: true
    index_keys:
    - language_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: select
      authority: HykuAddons::LanguageService
      include_blank: true
  prerequisites:
    type: string
    predicate: http://creativecommons.org/ns#Requirement
    multiple: false
    index_keys:
    - prerequisites_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  location:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/physicalLocation
    multiple: false
    index_keys:
    - location_tesim
    - location_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  longitude:
    type: string
    predicate: http://schema.org/longitude
    multiple: false
    index_keys:
    - longitude_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  latitude:
    type: string
    predicate: http://schema.org/latitude
    multiple: false
    index_keys:
    - latitude_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  georeferenced:
    type: string
    predicate: http://ogp.me/ns/class#boolean_str
    multiple: false
    index_keys:
    - georeferenced_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  time:
    type: string
    predicate: http://purl.org/dc/terms/temporal
    multiple: false
    index_keys:
    - time_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  irb_number:
    type: string
    predicate: http://purl.org/ontology/bibo/identifier
    multiple: false
    index_keys:
    - irb_number_tesim
    - irb_number_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  irb_status:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Status
    multiple: false
    index_keys:
    - irb_status_tesim
    - irb_status_sim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: false
    index_keys:
    - add_info_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  doi:
    doi:
    type: string
    predicate: http://purl.org/ontology/bibo/doi
    multiple: true
    index_keys:
    - doi_ssi
    form:
      required: false
      primary: true
      multiple: true
      type: text
