terms:
  - id: Rochester Regional Library Council
    term: Rochester Regional Library Council
    active: true
  - id: Villa Maria College
    term: Villa Maria College
    active: true
  - id: Western New York Library Resources Council
    term: Western New York Library Resources Council
    active: true
