terms:
  - id: Auraria Higher Education Center
    term: Auraria Higher Education Center
    active: true
  - id: Auraria Library
    term: Auraria Library
    active: true
  - id: Metropolitan State University of Denver
    term: Metropolitan State University of Denver
    active: true
  - id: Community College of Denver
    term: Community College of Denver
    active: true
  - id: University of Colorado Denver
    term: University of Colorado Denver
    active: true
