terms:
  - id: Blue Ridge
    term: Blue Ridge
    active: true
  - id: Cumming
    term: Cumming
    active: true
  - id: Dahlonega
    term: Dahlonega
    active: true
  - id: Gainesville
    term: Gainesville
    active: true
  - id: Oconee
    term: Oconee
    active: true