terms:
  - id: eng
    term: English
    active: true
  - id: fra
    term: French
    active: true
  - id: jpn
    term: Japanese
    active: true
  - id: spa
    term: Spanish
    active: true
  - id: vie
    term: Vietnamese
    active: true
