terms:
  - id: Accounting
    term: Accounting
    active: true
  - id: Administrative & Executive Offices
    term: Administrative & Executive Offices
    active: true
  - id: Art
    term: Art
    active: true
  - id: Asian Studies
    term: Asian Studies
    active: true
  - id: Biochemistry and Molecular Biology
    term: Biochemistry and Molecular Biology
    active: true
  - id: Biology
    term: Biology
    active: true
  - id: Business Administration
    term: Business Administration
    active: true
  - id: Center for Spatial Studies
    term: Center for Spatial Studies
    active: true
  - id: Chemistry
    term: Chemistry
    active: true
  - id: Communication Sciences & Disorders
    term: Communication Sciences & Disorders
    active: true
  - id: Computer Science
    term: Computer Science
    active: true
  - id: Counseling and Human Services
    term: Counseling and Human Services
    active: true
  - id: Creative Writing
    term: Creative Writing
    active: true
  - id: Economics
    term: Economics
    active: true
  - id: English Literature and Writing
    term: English Literature and Writing
    active: true
  - id: Environmental Studies
    term: Environmental Studies
    active: true
  - id: French
    term: French
    active: true
  - id: Geographic Information Science
    term: Geographic Information Science
    active: true
  - id: German
    term: German
    active: true
  - id: Graduate School of Theology
    term: Graduate School of Theology
    active: true
  - id: History
    term: History
    active: true
  - id: Human-Animal Studies
    term: Human-Animal Studies
    active: true
  - id: International Relations
    term: International Relations
    active: true
  - id: Johnston Center for Integrative Studies
    term: Johnston Center for Integrative Studies
    active: true
  - id: Latin American Studies
    term: Latin American Studies
    active: true
  - id: Leadership and Higher Education
    term: Leadership and Higher Education
    active: true
  - id: Library
    term: Library
    active: true
  - id: Liberal Studies
    term: Liberal Studies
    active: true
  - id: Mathematics
    term: Mathematics
    active: true
  - id: Media and Visual Culture Studies
    term: Media and Visual Culture Studies
    active: true
  - id: Music
    term: Music
    active: true
  - id: Philosophy
    term: Philosophy
    active: true
  - id: Physical Education
    term: Physical Education
    active: true
  - id: Physics
    term: Physics
    active: true
  - id: Political Science
    term: Political Science
    active: true
  - id: Psychology
    term: Psychology
    active: true
  - id: Public Policy
    term: Public Policy
    active: true
  - id: Race and Ethnic Studies
    term: Race and Ethnic Studies
    active: true
  - id: Religious Studies
    term: Religious Studies
    active: true
  - id: School of Business
    term: School of Business
    active: true
  - id: Sociology and Anthropology
    term: Sociology and Anthropology
    active: true
  - id: Spanish
    term: Spanish
    active: true
  - id: Teaching and Learning
    term: Teaching and Learning
    active: true
  - id: Theatre Arts
    term: Theatre Arts
    active: true
  - id: Women, Gender, and Sexuality Studies
    term: Women, Gender, and Sexuality Studies
    active: true
# Terms Added for Migration purposes
  - id: Engineering
    term: Engineering
    active: false
