terms:
- id: PhD
  term: Doctor of Philosophy
  active: true
- id: DBA
  term: Doctor of Business Administration
  active: true
- id: DClinPsy
  term: Doctor of Clinical Psychology
  active: true
- id: DDS
  term: Doctor of Dental Surgery
  active: true
- id: EdD
  term: Doctor of Education
  active: true
- id: DEdPsy
  term: Doctor of Educational Psychology
  active: true
- id: EngD
  term: Doctor of Engineering
  active: true
- id: DHRes
  term: Doctor of Health Research
  active: true
- id: HScD
  term: Doctor of Health Science
  active: true
- id: DLitt
  term: Doctor of Letters
  active: true
- id: DMin
  term: Doctor of Ministry
  active: true
- id: MD
  term: Doctor of Medicine
  active: true
- id: DMus
  term: Doctor of Music
  active: true
- id: OD
  term: Doctor of Optometry
  active: true
- id: DPhil
  term: Doctor of Philosophy
  active: false
- id: DPT
  term: Doctor of Physical Therapy
  active: true
- id: DrPH
  term: Doctor of Public Health
  active: true
- id: DSc
  term: Doctor of Science
  active: true
- id: DSocSci
  term: Doctor of Social Science
  active: true
- id: ProfDoc
  term: Doctor of Professional Studies
  active: true
- id: ThD
  term: Doctor of Theology
  active: true
- id: MA
  term: Master of Arts
  active: true
- id: MBA
  term: Master of Business Administration
  active: true
- id: MEd
  term: Master of Education
  active: true
- id: MLitt
  term: Master of Letters
  active: true
- id: MM
  term: Master of Music
  active: true
- id: MRes
  term: Master of Research
  active: true
- id: MSc
  term: Master of Science
  active: true
- id: MSN
  term: Master of Science in Nursing
  active: true
- id: MSt
  term: Master of Studies
  active: true
