terms:
- id: AA
  term: AA
  active: true
- id: AAS
  term: AAS
  active: true
- id: AS
  term: AS
  active: true
- id: BA
  term: BA
  active: true
- id: BBA
  term: BBA
  active: true
- id: BFA
  term: BFA
  active: true
- id: BS
  term: BS
  active: true
- id: DMin
  term: DMin
  active: true
- id: DO
  term: DO
  active: true
- id: Ed.D.
  term: Ed.D.
  active: true
- id: JD
  term: JD
  active: true
- id: MA
  term: MA
  active: true
- id: MArch
  term: MArch
  active: true
- id: MBA
  term: MBA
  active: true
- id: MD
  term: MD
  active: true
- id: MS
  term: MS
  active: true
- id: MSN
  term: MSN
  active: true
- id: PhD
  term: PhD
  active: true
- id: PPDPT
  term: PPDPT
  active: true
- id: STL
  term: STL
  active: true
- id: THM
  term: THM
  active: true
- id: Other
  term: Other
  active: true