terms:
  - id: Book
    term: Book
  - id: Magazine
    term: Magazine
  - id: Report
    term: Report
  - id: Student Newspaper
    term: Student Newspaper
  - id: Textbook or Casebook
    term: Textbook or Casebook