terms:
  - id: Thesis
    term: Thesis
  - id: Dissertation
    term: Dissertation
  - id: Capstone
    term: Capstone
  - id: DNP Project
    term: DNP Project
  - id: Honors Project
    term: Honors Project
  - id: Integral Honors Project
    term: Integral Honors Project
  - id: Master's Project - Nursing Program
    term: Master's Project - Nursing Program
  - id: Master's Project - Occupational Therapy Program
    term: Master's Project - Occupational Therapy Program
  - id: Master's Project - Physician Assistant Studies Program
    term: Master's Project - Physician Assistant Studies Program