terms:
  - id: Panel
    term: Panel
  - id: Paper Presentation
    term: Paper Presentation
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Research Paper
    term: Research Paper
  - id: Slide deck
    term: Slide deck
  - id: Symposium
    term: Symposium
  - id: Webinar
    term: Webinar
  - id: Other
    term: Other





