terms:
  - id: Journal article
    term: Journal article
  - id: Book review
    term: Book review
  - id: Editorial
    term: Editorial
  - id: Newspaper article
    term: Newspaper article
  - id: Conference Paper
    term: Conference Paper
  - id: Data paper
    term: Data paper
