terms:
  - id: Conference work
    term: Conference work
  - id: Paper
    term: Paper
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Report
    term: Report
  - id: Slides
    term: Slides
  - id: Webinar
    term: Webinar
