terms:
- id: Advisor
  term: Advisor
  active: true
- id: Animator
  term: Animator
  active: true
- id: Artist
  term: Artist
  active: true
- id: Author
  term: Author
  active: true
- id: Collaborative Doctoral Partner
  term: Collaborative Doctoral Partner
  active: true
- id: Collaborative Institution
  term: Collaborative Institution
  active: true
- id: Contact Person
  term: Contact Person
  active: true
- id: Contributor
  term: Contributor
  active: true
- id: Data Collector
  term: Data Collector
  active: true
- id: Data Curator
  term: Data Curator
  active: true
- id: Data Manager
  term: Data Manager
  active: true
- id: Designer
  term: Designer
  active: true
- id: Distributor
  term: Distributor
  active: true
- id: Editor
  term: Editor
  active: true
- id: Hosting Institution
  term: Hosting Institution
  active: true
- id: Illustrator
  term: Illustrator
  active: true
- id: Interviewee
  term: Interviewee
  active: true
- id: Interviewer
  term: Interviewer
  active: true
- id: Narrator
  term: Narrator
  active: true
- id: Photographer
  term: Photographer
  active: true
- id: Presenter
  term: Presenter
  active: true
- id: Producer
  term: Producer
  active: true
- id: Project Leader
  term: Project Leader
  active: true
- id: Project Manager
  term: Project Manager
  active: true
- id: Project Member
  term: Project Member
  active: true
- id: Publisher
  term: Publisher
  active: true
- id: Related Person
  term: Related Person
  active: true
- id: Researcher
  term: Researcher
  active: true
- id: Research Group
  term: Research Group
  active: true
- id: Rights Holder
  term: Rights Holder
  active: true
- id: Scientific Advisor
  term: Scientific Advisor
  active: true
- id: Sponsor
  term: Sponsor
  active: true
- id: Supervisor
  term: Supervisor
  active: true
- id: Transcriber
  term: Transcriber
  active: true
- id: Translator
  term: Translator
  active: true
- id: Videographer
  term: Videographer
  active: true
- id: Other
  term: Other
  active: true