terms:
 - id: Abstract Expressionist
   term: Abstract Expressionist
   active: true
 - id: African Sculpture Styles
   term: African Sculpture Styles
   active: true
 - id: Ancestral Puebloan
   term: Ancestral Puebloan
   active: true
 - id: Ancient
   term: Ancient
   active: true
 - id: Ancient African
   term: Ancient African
   active: true
 - id: Ancient American
   term: Ancient American
   active: true
 - id: Ancient Asian
   term: Ancient Asian
   active: true
 - id: Ancient British
   term: Ancient British
   active: true
 - id: Ancient Greek (culture or style)
   term: Ancient Greek (culture or style)
   active: true
 - id: Ancient Italian
   term: Ancient Italian
   active: true
 - id: Ancient Italian Architecture Styles
   term: Ancient Italian Architecture Styles
   active: true
 - id: Ancient Italian Sculpture Styles
   term: Ancient Italian Sculpture Styles
   active: true
 - id: Ancient Italian Wall Painting Styles
   term: Ancient Italian Wall Painting Styles
   active: true
 - id: Art Deco
   term: Art Deco
   active: true
 - id: Arts and Crafts (movement)
   term: Arts and Crafts (movement)
   active: true
 - id: British Renaissance-Baroque Architecture Styles
   term: British Renaissance-Baroque Architecture Styles
   active: true
 - id: Chinese Architecture Styles
   term: Chinese Architecture Styles
   active: true
 - id: Chinese Painting Styles
   term: Chinese Painting Styles
   active: true
 - id: Chippendale
   term: Chippendale
   active: true
 - id: Colonial African
   term: Colonial African
   active: true
 - id: Craftsman (style)
   term: Craftsman (style)
   active: true
 - id: Dada
   term: Dada
   active: true
 - id: Eclectic Style (general style)
   term: Eclectic Style (general style)
   active: true
 - id: Egyptian (ancient)
   term: Egyptian (ancient)
   active: true
 - id: Free Style (architecture)
   term: Free Style (architecture)
   active: true
 - id: French Medieval Architecture Styles
   term: French Medieval Architecture Styles
   active: true
 - id: German Medieval Architecture Styles
   term: German Medieval Architecture Styles
   active: true
 - id: Gothic (Medieval)
   term: Gothic (Medieval)
   active: true
 - id: Greek Sculpture Styles
   term: Greek Sculpture Styles
   active: true
 - id: Harlem Renaissance
   term: Harlem Renaissance
   active: true
 - id: Indian Architecture Styles
   term: Indian Architecture Styles
   active: true
 - id: Industrial Style (generic style)
   term: Industrial Style (generic style)
   active: true
 - id: International Style (modern European architecture style)
   term: International Style (modern European architecture style)
   active: true
 - id: Islamic Architectural Styles
   term: Islamic Architectural Styles
   active: true
 - id: Italian Medieval Styles
   term: Italian Medieval Styles
   active: true
 - id: Japanese Architecture Styles
   term: Japanese Architecture Styles
   active: true
 - id: Japanese Painting Styles
   term: Japanese Painting Styles
   active: true
 - id: Japanese Sculpture Styles
   term: Japanese Sculpture Styles
   active: true
 - id: Korean Styles
   term: Korean Styles
   active: true
 - id: Late Modernism
   term: Late Modernism
   active: true
 - id: Maya Area Architecture Styles
   term: Maya Area Architecture Styles
   active: true
 - id: Medieval Styles and Periods
   term: Medieval Styles and Periods
   active: true
 - id: Mexican Muralist (movement)
   term: Mexican Muralist (movement)
   active: true
 - id: Mid-Century Modernist
   term: Mid-Century Modernist
   active: true
 - id: Mission Style (Spanish Colonial Revival style)
   term: Mission Style (Spanish Colonial Revival style)
   active: true
 - id: Modern (style or period)
   term: Modern (style or period)
   active: true
 - id: Modern American
   term: Modern American
   active: true
 - id: Modern Movement
   term: Modern Movement
   active: true
 - id: Modern Style (Art Nouveau )
   term: Modern Style (Art Nouveau )
   active: true
 - id: Mughal Styles
   term: Mughal Styles
   active: true
 - id: Neo-Expressionist
   term: Neo-Expressionist
   active: true
 - id: Netherlandish Renaissance-Baroque styles
   term: Netherlandish Renaissance-Baroque styles
   active: true
 - id: Pop (fine arts styles)
   term: Pop (fine arts styles)
   active: true
 - id: Postmodern
   term: Postmodern
   active: true
 - id: Prairie School
   term: Prairie School
   active: true
 - id: Pre-Columbian North American Styles
   term: Pre-Columbian North American Styles
   active: true
 - id: Prehistoric African Rock Art Styles and Periods
   term: Prehistoric African Rock Art Styles and Periods
   active: true
 - id: Queen Anne Style
   term: Queen Anne Style
   active: true
 - id: Renaissance
   term: Renaissance
   active: true
 - id: Renaissance-Baroque Architecture Styles
   term: Renaissance-Baroque Architecture Styles
   active: true
 - id: Roman (ancient Italian culture or period)
   term: Roman (ancient Italian culture or period)
   active: true
 - id: Romantic (modern European styles)
   term: Romantic (modern European styles)
   active: true
 - id: Shingle Style
   term: Shingle Style
   active: true
 - id: Southwest (style)
   term: Southwest (style)
   active: true
 - id: Spanish Medieval Styles
   term: Spanish Medieval Styles
   active: true
 - id: Surrealist
   term: Surrealist
   active: true
 - id: Symbolist
   term: Symbolist
   active: true
