terms:
  - id: Administrative Law
    term: Administrative Law
    active: true
  - id: Banking and Finance Law
    term: Banking and Finance Law
    active: true
  - id: Business Organizations Law
    term: Business Organizations Law
    active: true
  - id: Christianity
    term: Christianity
    active: true
  - id: Common Law
    term: Common Law
    active: true
  - id: Conflict of Laws
    term: Conflict of Laws
    active: true
  - id: Constitutional Law
    term: Constitutional Law
    active: true
  - id: Consumer Protection Law
    term: Consumer Protection Law
    active: true
  - id: Courts
    term: Courts
    active: true
  - id: Criminal Law
    term: Criminal Law
    active: true
  - id: Criminal Procedure
    term: Criminal Procedure
    active: true
  - id: Engineering
    term: Engineering
    active: true
  - id: Environmental Design
    term: Environmental Design
    active: true
  - id: Estates and Trusts
    term: Estates and Trusts
    active: true
  - id: Evidence
    term: Evidence
    active: true
  - id: Family Law
    term: Family law
    active: true
  - id: First Amendment
    term: First Amendment
    active: true
  - id: Government Contracts
    term: Government Contracts
    active: true
  - id: History
    term: History
    active: true
  - id: Housing Law
    term: Housing Law
    active: true
  - id: Indigenous, Indian, and Aboriginal Law
    term: Indigenous, Indian, and Aboriginal Law
    active: true
  - id: Intellectual Property Law
    term: Intellectual Property Law
    active: true
  - id: International Law
    term: International Law
    active: true
  - id: International Trade Law
    term: International Trade Law
    active: true
  - id: Judges
    term: Judges
    active: true
  - id: Jurisprudence
    term: Jurisprudence
    active: true
  - id: Law and Economics
    term: Law and Economics
    active: true
  - id: Law and Gender
    term: Law and Gender
    active: true
  - id: Law and Race, Law and Religion
    term: Law and Race, Law and Religion
    active: true
  - id: Law and Society
    term: Law and Society
    active: true
  - id: Law Enforcement and Corrections
    term: Law Enforcement and Corrections
    active: true
  - id: Legal Education
    term: Legal Education
    active: true
  - id: Legal Ethics and Professional Responsibility
    term: Legal Ethics and Professional Responsibility
    active: true
  - id: Legal History
    term: Legal History
    active: true
  - id: Legal Profession
    term: Legal Profession
    active: true
  - id: Legal Writing and Research
    term: Legal Writing and Research
    active: true
  - id: Legislation
    term: Legislation
    active: true
  - id: Litigation
    term: Litigation
    active: true
  - id: Other
    term: Other
    active: true
  - id: Other Law
    term: Other Law
    active: true
  - id: Philosophy
    term: Philosophy
    active: true
  - id: Political Science
    term: Political Science
    active: true
  - id: Public Law and Legal Theory
    term: Public Law and Legal Theory
    active: true
  - id: Real Property Law
    term: Real Property Law
    active: true
  - id: Religion
    term: Religion
    active: true
  - id: Second Amendment
    term: Second Amendment
    active: true
  - id: Secured Transactions
    term: Secured Transactions
    active: true
  - id: Securities Law
    term: Securities Law
    active: true
  - id: Social and Behavioral Sciences
    term: Social and Behavioral Sciences
    active: true
  - id: Sociology
    term: Sociology
    active: true
  - id: Tax Law
    term: Tax Law
    active: true
  - id: Torts
    term: Torts
    active: true