terms:
  - term: Architectural Engineering
    id: Architectural Engineering
    active: true
  - term: Architecture
    id: Architecture
    active: true
  - term: Art History
    id: Art History
    active: true
  - term: Audio Engineering Technology
    id: Audio Engineering Technology
    active: true
  - term: Basic Science
    id: Basic Science
    active: true
  - term: Bioengineering
    id: Bioengineering
    active: true
  - term: Biology
    id: Biology
    active: true
  - term: Business Administration
    id: Business Administration
    active: true
  - term: Business Data Analytics
    id: Business Data Analytics
    active: true
  - term: Chemical Biology
    id: Chemical Biology
    active: true
  - term: Chemistry
    id: Chemistry
    active: true
  - term: Civil Engineering
    id: Civil Engineering
    active: true
  - term: Civil Engineering + Architecture
    id: Civil Engineering + Architecture
    active: true
  - term: Communication
    id: Communication
    active: true
  - term: Computer Engineering
    id: Computer Engineering
    active: true
  - term: Computer Engineering Technology and Management
    id: Computer Engineering Technology and Management
    active: true
  - term: Computer Science
    id: Computer Science
    active: true
  - term: Computer Science and Information Systems
    id: Computer Science and Information Systems
    active: true
  - term: Curriculum and Instruction
    id: Curriculum and Instruction
    active: true
  - term: Data Science
    id: Data Science
    active: true
  - term: Design and Planning
    id: Design and Planning
    active: true
  - term: Economics
    id: Economics
    active: true
  - term: Education
    id: Education
    active: true
  - term: Education and Human Development
    id: Education and Human Development
    active: true
  - term: Educational Leadership and Equity
    id: Educational Leadership and Equity
    active: true
  - term: Educational Leadership and Innovation
    id: Educational Leadership and Innovation
    active: true
  - term: Educational Studies and Research
    id: Educational Studies and Research
    active: true
  - term: Electrical Engineering
    id: Electrical Engineering
    active: true
  - term: Embedded Software Design
    id: Embedded Software Design
    active: true
  - term: Engineering
    id: Engineering
    active: true
  - term: English
    id: English
    active: true
  - term: English Literature
    id: English Literature
    active: true
  - term: Environmental Chemistry
    id: Environmental Chemistry
    active: true
  - term: Environmental Planning
    id: Environmental Planning
    active: true
  - term: Environmental Sciences
    id: Environmental Sciences
    active: true
  - term: Fine Arts
    id: Fine Arts
    active: true
  - term: Game Design
    id: Game Design
    active: true
  - term: Graphic Design
    id: Graphic Design
    active: true
  - term: Health and Behavioral Sciences
    id: Health and Behavioral Sciences
    active: true
  - term: Health Sciences
    id: Health Sciences
    active: true
  - term: History
    id: History
    active: true
  - term: Humanities
    id: Humanities
    active: true
  - term: Humanities and Social Sciences
    id: Humanities and Social Sciences
    active: true
  - term: Industrial Design
    id: Industrial Design
    active: true
  - term: Interior Design
    id: Interior Design
    active: true
  - term: Landscape Architecture
    id: Landscape Architecture
    active: true
  - term: Liberal Arts
    id: Liberal Arts
    active: true
  - term: Liberal Arts and Sciences
    id: Liberal Arts and Sciences
    active: true
  - term: Literature
    id: Literature
    active: true
  - term: Management Science and Information Systems
    id: Management Science and Information Systems
    active: true
  - term: Mathematical and Statistical Sciences
    id: Mathematical and Statistical Sciences
    active: true
  - term: Mathematical Sciences
    id: Mathematical Sciences
    active: true
  - term: Mathematics
    id: Mathematics
    active: true
  - term: Mathematics and Computer Science
    id: Mathematics and Computer Science
    active: true
  - term: Mechanical and Manufacturing Engineering Technology
    id: Mechanical and Manufacturing Engineering Technology
    active: true
  - term: Mechanical Engineering
    id: Mechanical Engineering
    active: true
  - term: Media Forensics
    id: Media Forensics
    active: true
  - term: Nursing
    id: Nursing
    active: true
  - term: Performing Arts
    id: Performing Arts
    active: true
  - term: Philosophy
    id: Philosophy
    active: true
  - term: Physics
    id: Physics
    active: true
  - term: Physics and Computer Science
    id: Physics and Computer Science
    active: true
  - term: Planning and Community Development
    id: Planning and Community Development
    active: true
  - term: Political Science
    id: Political Science
    active: true
  - term: Psychology
    id: Psychology
    active: true
  - term: Robotics Engineering
    id: Robotics Engineering
    active: true
  - term: Social Sciences
    id: Social Sciences
    active: true
  - term: Society and Environmentalism
    id: Society and Environmentalism
    active: true
  - term: Structural Engineering
    id: Structural Engineering
    active: true
  - term: Technical Communication
    id: Technical Communication
    active: true
  - term: Technological Humanities
    id: Technological Humanities
    active: true
  - term: Transportation Design
    id: Transportation Design
    active: true
  - term: Urban and Regional Planning
    id: Urban and Regional Planning
    active: true
  - term: Urban Design
    id: Urban Design
    active: true
  - term: Writing
    id: Writing
    active: true