terms:
 - id: Arboriculture and Landscape Management
   term: Arboriculture and Landscape Management
   active: true
 - id: Baking & Pastry Arts
   term: Baking & Pastry Arts
   active: true
 - id: Baking Arts & Service Management
   term: Baking Arts & Service Management
   active: true
 - id: Biology
   term: Biology
   active: true
 - id: Business Management
   term: Business Management
   active: true
 - id: Communication
   term: Communication
   active: true
 - id: Culinary Management
   term: Culinary Management
   active: true
 - id: Digital Marketing
   term: Digital Marketing
   active: true
 - id: Disaster Management & Response
   term: Disaster Management & Response
   active: true
 - id: Ecological Forest Management
   term: Ecological Forest Management
   active: true
 - id: Ecological Restoration
   term: Ecological Restoration
   active: true
 - id: Entrepreneurship
   term: Entrepreneurship
   active: true
 - id: Environmental Sciences
   term: Environmental Sciences
   active: true
 - id: Environmental Studies
   term: Environmental Studies
   active: true
 - id: Esports Management
   term: Esports Management
   active: true
 - id: Fisheries & Wildlife Sciences
   term: Fisheries & Wildlife Sciences
   active: true
 - id: Forest Biology
   term: Forest Biology
   active: true
 - id: Forest Operations 
   term: Forest Operations
   active: true
 - id: Forestry
   term: Forestry
   active: true
 - id: Government and Public Administration
   term: Government and Public Administration
   active: true
 - id: Hotel, Resort & Tourism Management
   term: Hotel, Resort & Tourism Management
   active: true
 - id: Human Health & the Environment
   term: Human Health & the Environment
   active: true
 - id: Human Resources Management
   term: Human Resources Management
   active: true
 - id: Integrative Studies
   term: Integrative Studies
   active: true
 - id: Management
   term: Management
   active: true
 - id: Natural Resource Conservation & Management
   term: Natural Resource Conservation & Management
   active: true
 - id: Natural Resources Conservation (MS)
   term: Natural Resources Conservation (MS)
   active: true
 - id: Natural Science
   term: Natural Science
   active: true
 - id: Neuroscience
   term: Neuroscience
   active: true
 - id: Park and Conservation Management
   term: Park and Conservation Management
   active: true
 - id: Psychology
   term: Psychology
   active: true
 - id: Recreation, Adventure Education & Leisure Management
   term: Recreation, Adventure Education & Leisure Management
   active: true
 - id: Restaurant Management
   term: Restaurant Management
   active: true
 - id: Sports & Event Management
   term: Sports & Event Management
   active: true
 - id: Sustainability
   term: Sustainability
   active: true
 - id: Sustainable Tourism Management (MPS)
   term: Sustainable Tourism Management (MPS)
   active: true