terms:
 - id: Accounting
   term: Accounting
   active: true
 - id: Appalachian Studies
   term: Appalachian Studies
   active: true  
 - id: Anthropology
   term: Anthropology
   active: true
 - id: Arts Administration
   term: Arts Administration
   active: true
 - id: Biology
   term: Biology
   active: true
 - id: Business
   term: Business
   active: true
 - id: Business Analysis
   term: Business Analysis
   active: true
 - id: Business Administration
   term: Business Administration
   active: true
 - id: Chemistry & Biochemistry
   term: Chemistry & Biochemistry
   active: true
 - id: Computer Science
   term: Computer Science
   active: true
 - id: Communication, Media, & Journalism
   term: Communication, Media, & Journalism
   active: true
 - id: Counseling
   term: Counseling
   active: true
 - id: Criminology
   term: Criminology
   active: true
 - id: Cybersecurity
   term: Cybersecurity
   active: true
 - id: Education
   term: Education
   active: true
 - id: Economics
   term: Economics
   active: true
 - id: Education Leadership
   term: Education Leadership
   active: true
 - id: Elementary & Special Education
   term: Elementary & Special Education
   active: true
 - id: English
   term: English
   active: true
 - id: Environmental Spatial Analysis
   term: Environmental Spatial Analysis
   active: true
 - id: Finance
   term: Finance
   active: true
 - id: Gender and Women's Studies
   term: Gender and Women's Studies
   active: true
 - id: History
   term: History
   active: true
 - id: Honors
   term: Honors
   active: true
 - id: Human Resource Management
   term: Human Resource Management
   active: true
 - id: Information Systems
   term: Information Systems
   active: true
 - id: Interdisciplinary Healthcare
   term: Interdisciplinary Healthcare
   active: true
 - id: Interdisciplinary Studies
   term: Interdisciplinary Studies
   active: true
 - id: Interdisciplinary Studies/University
   term: Interdisciplinary Studies/University
   active: true
 - id: Kinesiology
   term: Kinesiology
   active: true
 - id: Law
   term: Law
   active: true
 - id: Legal Systems
   term: Legal Systems
   active: true
 - id: Library Science
   term: Library Science
   active: true
 - id: Management
   term: Management
   active: true
 - id: Marketing
   term: Marketing
   active: true
 - id: Mathematics
   term: Mathematics
   active: true
 - id: Middle Grades, Secondary, & Science Education
   term: Middle Grades, Secondary, & Science Education
   active: true
 - id: Military Science
   term: Military Science
   active: true
 - id: Music
   term: Music
   active: true
 - id: Nursing
   term: Nursing
   active: true
 - id: Occupational Therapy
   term: Occupational Therapy
   active: true
 - id: Peace & Global Studies
   term: Peace & Global Studies
   active: true
 - id: Philosophy
   term: Philosophy
   active: true
 - id: Physical Therapy
   term: Physical Therapy
   active: true
 - id: Physician Assistant Studies
   term: Physician Assistant Studies
   active: true
 - id: Physics
   term: Physics
   active: true
 - id: Political Science
   term: Political Science
   active: true
 - id: Psychology
   term: Psychology
   active: true
 - id: Religious Studies
   term: Religious Studies
   active: true
 - id: Risk Management & Insurance
   term: Risk Management & Insurance
   active: true
 - id: Sociology
   term: Sociology
   active: true
 - id: Theatre
   term: Theatre
   active: true
 - id: Visual Arts
   term: Visual Arts
   active: true
 - id: World Languages, Literatures, & Cultures
   term: World Languages, Literatures, & Cultures
   active: true