terms:
 - id: Administration, Curriculum, and Supervision
   term: Administration, Curriculum, and Supervision
   active: true
 - id: Anthropology
   term: Anthropology
   active: true
 - id: Applied Language
   term: Applied Language
   active: true
 - id: Applied Mathematics
   term: Applied Mathematics
   active: true
 - id: Architecture
   term: Architecture
   active: true
 - id: Art History
   term: Art History
   active: true
 - id: Basic Science
   term: Basic Science
   active: true
 - id: Bioengineering
   term: Bioengineering
   active: true
 - id: Biology
   term: Biology
   active: true
 - id: Business
   term: Business
   active: true
 - id: Chemistry
   term: Chemistry
   active: true
 - id: Civil Engineering
   term: Civil Engineering
   active: true
 - id: Clinical Health Psychology
   term: Clinical Health Psychology
   active: true
 - id: Communication
   term: Communication
   active: true
 - id: Communication and Theatre
   term: Communication and Theatre
   active: true
 - id: Computer Science
   term: Computer Science
   active: true
 - id: Computer Science and Engineering
   term: Computer Science and Engineering
   active: true
 - id: Computer Science and Information Systems
   term: Computer Science and Information Systems
   active: true
 - id: Counseling
   term: Counseling
   active: true
 - id: Counseling Psychology
   term: Counseling Psychology
   active: true
 - id: Criminal Justice
   term: Criminal Justice
   active: true
 - id: Curriculum and Instruction
   term: Curriculum and Instruction
   active: true
 - id: Design and Planning
   term: Design and Planning
   active: true
 - id: Economics
   term: Economics
   active: true
 - id: Education
   term: Education
   active: true
 - id: Education and Human Development
   term: Education and Human Development
   active: true
 - id: Educational Leadership and Equity
   term: Educational Leadership and Equity
   active: true
 - id: Educational Leadership and Innovation
   term: Educational Leadership and Innovation
   active: true
 - id: Educational Studies and Research
   term: Educational Studies and Research
   active: true
 - id: Electrical Engineering
   term: Electrical Engineering
   active: true
 - id: Engineering
   term: Engineering
   active: true
 - id: English
   term: English
   active: true
 - id: English Literature
   term: English Literature
   active: true
 - id: English, Rhetorical Theory, and Teaching Writing
   term: English, Rhetorical Theory, and Teaching Writing
   active: true
 - id: Environmental Planning
   term: Environmental Planning
   active: true
 - id: Environmental Sciences
   term: Environmental Sciences
   active: true
 - id: Fine Arts
   term: Fine Arts
   active: true
 - id: Geography
   term: Geography
   active: true
 - id: Geology
   term: Geology
   active: true
 - id: Health and Behavioral Sciences
   term: Health and Behavioral Sciences
   active: true
 - id: Health Sciences
   term: Health Sciences
   active: true
 - id: Historic Preservation
   term: Historic Preservation
   active: true
 - id: History
   term: History
   active: true
 - id: Humanities
   term: Humanities
   active: true
 - id: Humanities and Social Sciences
   term: Humanities and Social Sciences
   active: true
 - id: Integrated Sciences
   term: Integrated Sciences
   active: true
 - id: Integrative Biology
   term: Integrative Biology
   active: true
 - id: Integrative Sciences
   term: Integrative Sciences
   active: true
 - id: International Studies
   term: International Studies
   active: true
 - id: Landscape Architecture
   term: Landscape Architecture
   active: true
 - id: Languages/Linguistics
   term: Languages/Linguistics
   active: true
 - id: Leadership for Educational Equity
   term: Leadership for Educational Equity
   active: true
 - id: Liberal Arts
   term: Liberal Arts
   active: true
 - id: Liberal Arts and Sciences
   term: Liberal Arts and Sciences
   active: true
 - id: Literature
   term: Literature
   active: true
 - id: Management Science and Information Systems
   term: Management Science and Information Systems
   active: true
 - id: Mathematical and Statistical Sciences
   term: Mathematical and Statistical Sciences
   active: true
 - id: Mathematical Sciences
   term: Mathematical Sciences
   active: true
 - id: Mathematics
   term: Mathematics
   active: true
 - id: Mathematics Education
   term: Mathematics Education
   active: true
 - id: Mechanical Engineering
   term: Mechanical Engineering
   active: true
 - id: Media Forensics
   term: Media Forensics
   active: true
 - id: Music
   term: Music
   active: true
 - id: Performing arts
   term: Performing arts
   active: true
 - id: Philosophy
   term: Philosophy
   active: true
 - id: Planning and Community Development
   term: Planning and Community Development
   active: true
 - id: Political Science
   term: Political Science
   active: true
 - id: Psychology
   term: Psychology
   active: true
 - id: Public Administration
   term: Public Administration
   active: true
 - id: Public Affairs
   term: Public Affairs
   active: true
 - id: Public History
   term: Public History
   active: true
 - id: Recording Arts
   term: Recording Arts
   active: true
 - id: School Psychology
   term: School Psychology
   active: true
 - id: Social Sciences
   term: Social Sciences
   active: true
 - id: Society and Environmentalism
   term: Society and Environmentalism
   active: true
 - id: Sociology
   term: Sociology
   active: true
 - id: Spanish
   term: Spanish
   active: true
 - id: Structural Engineering
   term: Structural Engineering
   active: true
 - id: Technical Communication
   term: Technical Communication
   active: true
 - id: Urban and Regional Planning
   term: Urban and Regional Planning
   active: true
 - id: Urban Design
   term: Urban Design
   active: true
 - id: Writing
   term: Writing
   active: true
